add tableView customCell contents that are category and date.
app-dojo-salon/ToDoAppEx pull request #15
Opened 2021-05-10 10:56 UTC by Nao-RandD

## 変更点
TableViewのカスタムセルを仕様にそって変更した。

## どうやって使うか
StoryBoardのtodoItem(カスタムセル)の
それぞれのcategory, startData, endDateとして、
UI Labelを参照してTableViewに反映させる。

## なぜ変更/追加したか
アプリとして管理したいタスクのコンテンツが追加されたため。

## スクショ(UI変更がある場合)
![Simulator Screen Shot - TestDevice-iPhone11 - 2021-05-10 at 19 45 41](https://user-images.githubusercontent.com/72324850/117648791-a0d83980-b1c9-11eb-9ba4-933e0b0913da.png)

## 備考
編集画面での実装によって、セルへの反映方法は変化すると思います。
そのため、タイトル部以外はデフォルトの初期値での表示になっています。

編集画面での実装でRealmの要素追加、TableViewへの表示反映の実装を合わせてやるほうがスムーズと判断しました。

2021-05-10 19:55 UTC, minmin0530 commented
@Nao-RandD 
iPhone12 で試すとリストがはみ出ていました。AutoLayoutを効かせて欲しいです。
<img width="564" alt="スクリーンショット 2021-05-11 4 53 42" src="https://user-images.githubusercontent.com/599842/117716870-0ef61e00-b215-11eb-9bfe-ed17ea03cec2.png">

2021-05-10 19:59 UTC, minmin0530 requested changes
iPhone12 で試すとリストがはみ出ていました。AutoLayoutを効かせて欲しいです。

2021-05-16 00:04 UTC, Nao-RandD commented
変更した内容をpushしています。
iPhone11と同様にiPhone12でも
UIが正常に表示されるようにしました。

![Simulator Screen Shot - TestDevice-iPhone11 - 2021-05-16 at 09 01 08](https://user-images.githubusercontent.com/72324850/118381425-a8626d00-b625-11eb-8e35-b3d96bcd9b29.png)
![Simulator Screen Shot - iPhone 12 - 2021-05-16 at 09 01 09](https://user-images.githubusercontent.com/72324850/118381426-ab5d5d80-b625-11eb-86ae-018e777ad0f2.png)

2021-05-16 01:46 UTC, minmin0530 approved these changes
LGTM!
カテゴリと日付の追加、ありがとうございます。

2021-05-16 01:46 UTC, merged