ホーム画面のTableViewの見た目を調整
app-dojo-salon/ToDoAppEx pull request #35
Opened 2022-02-05 02:50 UTC by Nao-RandD

## 変更点
- ホーム画面の見た目を調整

## どうやって使うか
- ログインしてホーム画面を表示

## なぜ変更/追加したか
- 既存のUIの表示だと文字が小さく見ずらいため

## スクショ(UI変更がある場合)
![Simulator Screen Shot - TestDevice - 2022-02-05 at 11 45 19](https://user-images.githubusercontent.com/72324850/152626182-e5dcb556-69a0-474a-add1-7ab741fad544.png)

## 備考
- 区切り線が左側で切れていたのはUI構成ではなく、TableViewの設定の問題でした

2022-02-05 04:02 UTC, minmin0530 requested changes
細かい指摘項目ですが、修正をお願いします。

2022-02-05 04:02 UTC, minmin0530 commented on ToDoAppEx/ViewController/HomeViewController.swift
> +    private func setTableViewCinfig() {
@Nao-RandD 命名がCinfigになっていますが、Configのタイポでしょうか？

2022-02-05 04:02 UTC, minmin0530 commented on ToDoAppEx/ViewController/HomeViewController.swift
> +          realm.delete(todoList[index])
@Nao-RandD インデントが全体と揃ってなかったので、修正をお願いします。

2022-02-06 01:33 UTC, Nao-RandD commented on ToDoAppEx/ViewController/HomeViewController.swift
> +    private func setTableViewCinfig() {
@minmin0530 
タイポですね、、、
ありがとうございます！
修正しておきます

2022-02-06 01:34 UTC, Nao-RandD commented on ToDoAppEx/ViewController/HomeViewController.swift
> +          realm.delete(todoList[index])
@minmin0530 
ありがとうございます！
修正します

2022-02-21 10:40 UTC, minmin0530 approved these changes
修正ありがとうございます😄
LGTM

2022-02-21 10:40 UTC, merged